### ISSUE TITLE
ts-top execution controller list has a fixed count

### ISSUE THREAD

**Issue by macgyver603** [godber/teraslice-top#15] opened 2020-01-04 00:51 UTC
Starting with `v0.62.2`, the `?size` parameter on all 5 of the `txt` Teraslice endpoints work as expected. While having the worker list truncated for a large cluster is quite nice, it would also be valuable to be able to alter the count for the execution controllers. 

The simplest solution would be to add an argument to change the number of ECs shown, but it might be worth adding a way to change the counts for the other endpoints as well.

**Comment by godber** [comment] 2020-01-08 00:28
In `v1.0.7` this has been resolved by removing the `?size=` constraint altogether from the Slicers section.  This means it will show up to 100 slicers.

The way we've used `ts-top` has evolved to the point where we rely upon it showing ALL of the running jobs.  Of course after we hit more than 100 running jobs on a cluster this change won't work as intended, but hopefully we'll have replaced ts-top by then.

**Closed as completed by godber** 2020-01-08 00:28 UTC
